### ISSUE TITLE
no

### ISSUE THREAD

**Issue by MEEPofFaith** [RebornTrack970/Extra-Sand-HACK#1]
"O LORD, bless this Thy hand grenade, that with it Thou mayest blow Thine enemies to tiny bits, in Thy mercy." And the LORD did grin, and the people did feast upon the lambs and sloths and carp and anchovies and orangutans and breakfast cereals, and fruit bats and large chu... ("skip a bit, brother") And the LORD spake, saying, "First shalt thou take out the Holy Pin. Then shalt thou count to three, no more, no less. Three shall be the number thou shalt count, and the number of the counting shall be three. Four shalt thou not count, neither count thou two, excepting that thou then proceed to three. Five is right out. Once the number three, being the third number, be reached, then lobbest thou thy Holy Hand Grenade of Antioch towards thy foe, who, being naughty in My sight, shall snuff it."

**Comment by MEEPofFaith** [comment]
Also, you can't build something that's 1 sand because you can't put sand in your core.

**Comment by braainsiogame** [comment]
go fuck yourself
Items.sand.ItemType.material

**Comment by MEEPofFaith** [comment]
Couldn't you have just made a fork instead...

**Comment by RebornTrack970** [comment]
What?

**Comment by RebornTrack970** [comment]
Sry Meep i made a fork but than i changed it there is a forked version too.
